config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :create, :new] do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in:
    %W(chinese italian japanese french belgian) }

  def average_rating
    rating_sum = 0
    reviews.each do |review|
      rating_sum += review.rating
    end
    (rating_sum / reviews.length).round(2)
  end

  def reviews_present?
    reviews.empty? == false
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, :content, :rating, presence: true
  validates :rating, numericality:
  { only_integer: true, greater_than_or_equal_to: 0, less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all

  end

  def show
    @review = Review.new
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/restaurants">All Restaurants</a>
      <a class="navbar-brand" href="/restaurants/new">Add Restaurant</a>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <ul>
  <% @restaurants.each do |restaurant| %>
    <div class="restaurant-card">
      <li>
        <div class="row justify-content-between">
          <%= link_to restaurant_path(restaurant) do%>
            <h4><%= restaurant.name.capitalize %></h4>
          <% end %>
          <p> <%= restaurant.address %></p>
        </div>
        <% if restaurant.reviews_present? %>
          <p>
            <% restaurant.average_rating.times do %>
              <span><i class="fas fa-star"></i></span>
            <% end %>
            <% (5 - restaurant.average_rating).times do %>
              <span><i class="far fa-star"></i></span>
            <% end %>
           (<%= restaurant.reviews.length %> reviews)</p>
        <% else %>
          <p>No reviews yet</p>
        <% end %>
      </li>
    </div>
  <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name%>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.submit "Create Restaurant" %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h2 class="card-title"><%= @restaurant.name.capitalize %></h3>
      <h5 class="card-title"><%= @restaurant.address %></h5>
      <h5 class="card-title"><%= @restaurant.category.capitalize %></h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <%= link_to new_restaurant_review_path(@restaurant) do %>
        <button class="btn btn-primary">Leave Review</button>
      <% end %>
    </div>
  </div>
  <h2>Reviews</h2>
  <%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label "Add a review" %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit Review" %>
  <% end %>
  <% @restaurant.reviews.each do |review| %>
    <ul>
      <li>
        <div class="card">
          <div class="card-body">
            <p><%= review.content %></p>
            <p>
              <% @restaurant.average_rating.times do %>
                <span><i class="fas fa-star"></i></span>
              <% end %>
              <% (5 - @restaurant.average_rating).times do %>
                <span><i class="far fa-star"></i></span>
              <% end %>
            </p>
          </div>
        </div>
      </li>
    </ul>
  <% end %>
</div>

<<!-- h1></h1>
<h4><%= @restaurant.category %></h4>
<h4></h4>
<% if @restaurant.phone_number %>
<p><%= @restaurant.phone_number %></p>
<% end %>
<%= link_to "review", new_restaurant_review_path(@restaurant) %>
<% @restaurant.reviews.each do |review| %>
<ul>
  <li>
    <%= review.content %>
    <%= review.rating %>
  </li>
</ul>
<% end %> -->

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit "Submit Review" %>
<% end %>